apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-peremoga-content-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-peremoga-content
    spec:
      containers:
        - name: grpc-content-service
          image: gcr.io/alien-fold-180922/grpc-content:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CONTENT_RESOURCE
              value: "peremoga.txt"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-peremoga-content-service
spec:
  type: LoadBalancer
  selector:
    app: grpc-peremoga-content
  ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP
---
